use team03;

insert into events ( event_id, user_id, event_name, latitude, longitude, start_time, end_time, location, list_description, isprivate, details) values (null,0,'Beach Party', 33.6407,-117.978,'2013-11-12 04:00:00','2013-11-12 12:00:00','A Beach','Bring a towel and sodas!',false,'This event is hosted by the swimming club and will include beach volleyball and a raffle for awesome things.');

insert into events ( event_id, user_id, event_name, latitude, longitude, start_time, end_time, location, list_description, isprivate, details) values (null,0,'Study Group for MATH 112', 39.7504,-105.224,'2013-11-12 04:00:00','2013-11-12 12:00:00','Vanderwerker Student Lounge','Come and join us in our calculus adventures!',false,'Everyone is encouraged to join us. We will be studying for the upcoming test in Calculus I');

insert into events ( event_id, user_id, event_name, latitude, longitude, start_time, end_time, location, list_description, isprivate, details) values (null,0,'Mountain Hike', 38.8433,-105.042,'2013-11-12 04:00:00','2013-11-12 12:00:00','Pikes Peak','Let\'s go and climb a mountain!',false,'The ORC wants you to come and climb Pikes Peak with us! Sure on google maps it looks like the event creator picked a deadly and tragic route, but who trusts google maps anymore?');

insert into events ( event_id, user_id, event_name, latitude, longitude, start_time, end_time, location, list_description, isprivate, details) values (null,0,'Video Game Convention ', 35.6296,139.727,'2013-11-12 04:00:00','2013-11-12 12:00:00','Japan','Come and meet your favorite Indie Game Developers!',false,'The video game convention tickets can be found online at ticketsByTheBucket.org. Get them while they are still only $60,000.');
  
insert into events ( event_id, user_id, event_name, latitude, longitude, start_time, end_time, location, list_description, isprivate, details) values (null,0,'Kappa Sigma Foam Party', 39.746961,-105.223191,'2013-04-05 21:00:00','2013-04-06 4:00:00','Kappa Sigma','E-Days Foam Party, Friday, April 5th!!',false,'Hey everyone! E-Days is right around the corner so that means it\'s time for Kappa ∑igma\'s annual Foam Party!! Blacklights, glow paint, swimsuits, and flip flops. Come prepared because you\'re going to get WET! In years past Foam Party has been free, this year is going to be a little different. We decided that this year we will be selling tickets to our Foam Party to raise money and awareness for a cause near and dear to our hearts; The Military Hero\'s Campaign. Kappa Sigma\'s Military Heroes Campaign was designed to honor and aid the thousands of wounded military veterans returning from active duty and their families during rehabilitation. We will be pre-selling wristbands for $3 each in the Student Center from 11am-1pm on March 28th & 29th and April 1st, 2nd, and 3rd. We will also be charging $5 at the door on the night of Foam Party. For those feeling extra charitable there will be the opportunity for extra donations at the event and a bow to show your generosity! If you\'re not able to make it to the Student Center to purchase tickets, then you can contact jwahlbri@mymail.mines.edu or lumyers@mymail.mines.edu and we can work something out.Doors open at 9:00pm, immediately after MasqueRave, at the Kappa Sigma House. There will be 3 live DJ\'s playing throughout the night. The music will be Electronic/House/Dubstep, so come prepared to dance the night away for a great cause! The house will be dry for the event so alcohol will not be provided or allowed in the house. ');
